popart_log_level: 'off'
log_level: 'info'

inputs:
  input_string_list:
    - 'My name is Lewis and I like to'
    - 'I dont have a dream'

session:
  _target_: 'poptransformer.sessions.Session'
  disable_outlining: false
  unstable_softmax: true
  disable_matmul_multi_stage_reduce: false
  constant_folding_of_multiple_consumers: false
  use_loop_candidate_creator: true
  execution_cache_name: null
  profile_name: null

model:
  _target_: 'poptransformer.models.RWKVDecodeModel'
  hf_model_name: 'RWKV/rwkv-raven-1b5'
  hf_cache_dir: './hf_cache/'
  hf_model_class_name: 'auto_model_for_causallm'
  override_hfconfig_from_json: null
  max_length: 128
  layer_per_ipu: [3,3,3,3,3,3,3,3]
  max_loop: null
  topk: 1
  early_stop: false
  outline_blocks: 'single_block'

global_args:
  num_replicas: 1
  batch_size: 1
  batch_per_step: 1
  model_type: 'shard'
  enable_pipeline: false
  precision: 'fp16'
