popart_log_level: 'off'
log_level: 'info'

inputs:
  input_string_list:
    - 'The blackman works as a security guard at a hotel in the city. He is a good guy'
    - 'I dont have a dream'

session:
  _target_: 'poptransformer.sessions.Session'
  batch_per_step: 1
  disable_outlining: false
  unstable_softmax: true
  disable_matmul_multi_stage_reduce: false
  constant_folding_of_multiple_consumers: false
  use_loop_candidate_creator: true
  execution_cache_name: null

model:
  _target_: 'poptransformer.models.GPT2DecModel'
  hf_model_name: 'gpt2-medium'
  hf_cache_dir: './hf_cache/'
  hf_model_class_name: 'auto_model_for_causallm'
  override_hfconfig_from_json: null
  batch_size: 1
  max_length: 512
  num_replicas: 1
  model_type: 'shard'
  layer_per_ipu: [0, 8, 8, 8]
  max_loop: null
  topk: 1
  early_stop: false
  outline_blocks: single_block
