popart_log_level: 'off'
log_level: 'info'

inputs:
  input_string: '晚上睡不着应该怎么办'
  use_history: False

session:
  _target_: 'poptransformer.sessions.Session'
  disable_outlining: false
  unstable_softmax: false
  disable_matmul_multi_stage_reduce: false
  constant_folding_of_multiple_consumers: false
  use_loop_candidate_creator: true
  execution_cache_name: './popef_cache_dir'

model:
  _target_: 'poptransformer.models.ChatGLM2DecModel'
  hf_model_name: 'THUDM/chatglm2-6b'
  hf_cache_dir: './hf_cache/'
  hf_model_class_name: 'auto_model'
  override_hfconfig_from_json: null

  input_length: 1
  max_length: 32
  layer_per_ipu: [14, 14]
  max_loop: null
  topk: 1
  early_stop: false
  outline_blocks: 'multi_block'

global_args:
  num_replicas: 4
  batch_size: 1
  batch_per_step: 1
  model_type: 'tp'
  enable_pipeline: false
  precision: 'int4'

